-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "Zip" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cartNumber" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "email" TEXT NOT NULL DEFAULT 'test@test.com',
ADD COLUMN     "phone" INTEGER NOT NULL DEFAULT 11122221212,
ADD COLUMN     "region" TEXT NOT NULL DEFAULT 'ktm';
